# path.n: NAMESPACE
# path.d: DESCRIPTION
# dir.r: R
# dir.v: vignettes
# dir.t: tests
# extra.suggests: yes
# pkg_ignore: ~
# document: yes
# normalize: yes
# inside_rmd: no
# must.exist: yes
# check_if_suggests_is_installed: yes
path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests

extra.suggests: true
pkg_ignore: null
document: true
normalize: true
inside_rmd: false
must.exist: true
check_if_suggests_is_installed: true
